/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import config.Config;
import dao.IDao;
import entities.Salle;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tecra
 */
public class SalleForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form SalleForm
     */
    IDao<Salle> dao2=null;
    DefaultTableModel model2=null;
    int Id= -1;
        private static SalleForm sf;
    public SalleForm() {
        initComponents();
        model2=(DefaultTableModel) jTableSalle.getModel();
          
        try {
            dao2 =(IDao<Salle>) Naming.lookup("rmi://"+Config.ip+":"+Config.port+"/dao2");
            loadSalle();
        } catch (NotBoundException ex) {
            Logger.getLogger(SalleForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(SalleForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(SalleForm.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    public void loadSalle(){
        try {
            model2.setRowCount(0);
            for (Salle s : dao2.findAll())
                model2.addRow(new Object[]{
                    s.getId(),
                    s.getCode(),
                   
                }); } catch (RemoteException ex) {
            Logger.getLogger(MachineForm.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        codejLabel1 = new javax.swing.JLabel();
        codeText = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        AjouterjButton1 = new javax.swing.JButton();
        ModifierjButton2 = new javax.swing.JButton();
        supprimerjButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSalle = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("gestion des salles");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("information salle"));

        codejLabel1.setText("code:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(codejLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(codeText, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codejLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Actions"));

        AjouterjButton1.setText("Ajouter");
        AjouterjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterjButton1ActionPerformed(evt);
            }
        });

        ModifierjButton2.setText("Modifier");
        ModifierjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierjButton2ActionPerformed(evt);
            }
        });

        supprimerjButton3.setText("Supprimer");
        supprimerjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerjButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(supprimerjButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModifierjButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AjouterjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AjouterjButton1)
                .addGap(18, 18, 18)
                .addComponent(ModifierjButton2)
                .addGap(18, 18, 18)
                .addComponent(supprimerjButton3)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Liste des salles"));

        jTableSalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "code"
            }
        ));
        jTableSalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSalleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSalle);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AjouterjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterjButton1ActionPerformed
        // TODO add your handling code here:
        String code = codeText.getText();

    try {
        // Créez une nouvelle instance de Salle avec le code et ajoutez-la à la base de données
        Salle salle = new Salle();
        salle.setCode(code);
        if (dao2.create(salle)) {
            JOptionPane.showMessageDialog(this, "Salle ajoutée avec succès");
            loadSalle(); // Rechargez la liste des salles
        } else {
            JOptionPane.showMessageDialog(this, "Échec de l'ajout de la salle");
        }
    } catch (RemoteException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erreur : " + ex.getMessage());
    }

    // Après l'ajout réussi, vous pouvez vider le champ de texte
    codeText.setText("");
                     
    }//GEN-LAST:event_AjouterjButton1ActionPerformed

    private void ModifierjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierjButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTableSalle.getSelectedRow();
    if (selectedRow != -1) {
        try {
            // Récupérez l'ID de la salle sélectionnée
            int salleId = (int) jTableSalle.getValueAt(selectedRow, 0);

            // Récupérez le nouveau code de la salle à partir du champ de texte
            String newCode = codeText.getText();

            // Récupérez la salle à partir de la base de données en utilisant l'ID
            Salle salleToUpdate = dao2.findById(salleId);

            // Mettez à jour le code de la salle
            salleToUpdate.setCode(newCode);

            // Mettez à jour la salle dans la base de données
            if (dao2.update(salleToUpdate)) {
                JOptionPane.showMessageDialog(this, "Salle modifiée avec succès");
                loadSalle(); // Rechargez la liste des salles
            } else {
                JOptionPane.showMessageDialog(this, "Échec de la modification de la salle");
            }
        } catch (RemoteException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erreur : " + ex.getMessage());
        }
    }

    // Après la modification réussie, vous pouvez vider le champ de texte
    codeText.setText("");
                                              

    }//GEN-LAST:event_ModifierjButton2ActionPerformed

     public static SalleForm getInstance() {
        if (sf == null) {
            sf = new SalleForm();
        }
        return sf;
    }
    
    private void supprimerjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerjButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTableSalle.getSelectedRow();
    if (selectedRow != -1) {
        try {
            // Récupérez l'ID de la salle sélectionnée
             int reponse =JOptionPane.showConfirmDialog(this, "veullez vous vraiment supprimé ?");
            int salleId = (int) jTableSalle.getValueAt(selectedRow, 0);

            // Récupérez la salle à partir de la base de données en utilisant l'ID
            Salle salleToDelete = dao2.findById(salleId);

            // Supprimez la salle de la base de données
            if (dao2.delete(salleToDelete)) {
                JOptionPane.showMessageDialog(this, "Salle supprimée avec succès");
                loadSalle(); // Rechargez la liste des salles
            } else {
                JOptionPane.showMessageDialog(this, "Échec de la suppression de la salle");
            }
        } catch (RemoteException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erreur : " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_supprimerjButton3ActionPerformed

    private void jTableSalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSalleMouseClicked
        // TODO add your handling code here:
          Id = Integer.parseInt(jTableSalle.getValueAt( jTableSalle.getSelectedRow(), 0).toString());
    }//GEN-LAST:event_jTableSalleMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjouterjButton1;
    private javax.swing.JButton ModifierjButton2;
    private javax.swing.JTextField codeText;
    private javax.swing.JLabel codejLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSalle;
    private javax.swing.JButton supprimerjButton3;
    // End of variables declaration//GEN-END:variables
}
